import { ref } from "vue";
import { v4 as uuidv4 } from "uuid";
import { GlobalTexts as t } from "@/app/locale/ru";
import { BlockSettings, ListVariablesType } from "@/entities/form";

const variables: ListVariablesType[] = [
  { value: uuidv4(), label: "Вариант 1" },
];
const DEFAULT_REQUIRED_FIELD = false;
const DEFAULT_DEFAULT_VALUE = "";

export const BLOCKS_LIST = ref<BlockSettings[]>([
  {
    id: uuidv4(),
    type: "text",
    icon: t.blocks.icons.shortTextIcon,
    title: t.blocks.title.shortText,
    subtitle: t.blocks.title.shortText,
    supportText: t.blocks.support.shortText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { defaultValue: DEFAULT_DEFAULT_VALUE },
  },
  {
    id: uuidv4(),
    type: "textarea",
    icon: t.blocks.icons.longTextIcon,
    title: t.blocks.title.longText,
    subtitle: t.blocks.title.longText,
    supportText: t.blocks.support.longText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { defaultValue: DEFAULT_DEFAULT_VALUE },
  },
  {
    id: uuidv4(),
    type: "clear_text",
    icon: t.blocks.icons.clearTextIcon,
    title: t.blocks.title.clearText,
    subtitle: t.blocks.title.clearText,
    supportText: t.blocks.support.clearText,
    requiredField: DEFAULT_REQUIRED_FIELD,
  },
  {
    id: uuidv4(),
    type: "radio",
    icon: t.blocks.icons.radioIcon,
    title: t.blocks.title.radioText,
    subtitle: t.blocks.title.radioText,
    supportText: t.blocks.support.radioText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { listLooks: "Плитка", variables },
  },
  {
    id: uuidv4(),
    type: "multiple_select",
    icon: t.blocks.icons.multipleIcon,
    title: t.blocks.title.multipleSelectText,
    subtitle: t.blocks.title.multipleSelectText,
    supportText: t.blocks.support.multipleSelectText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { variables },
  },
  {
    id: uuidv4(),
    type: "color",
    icon: t.blocks.icons.colorIcon,
    title: t.blocks.title.colorText,
    subtitle: t.blocks.title.colorText,
    supportText: t.blocks.support.colorText,
    requiredField: DEFAULT_REQUIRED_FIELD,
  },
  {
    id: uuidv4(),
    type: "divider",
    icon: t.blocks.icons.dividerIcon,
    title: t.blocks.title.dividerText,
    supportText: t.blocks.support.dividerText,
    isSpecial: true,
    settings: { listLooks: "Линия" },
  },
  {
    id: uuidv4(),
    type: "checkbox",
    icon: t.blocks.icons.checkBoxIcon,
    title: t.blocks.title.checkIconText,
    subtitle: t.blocks.title.checkIconText,
    supportText: t.blocks.support.checkBoxText,
    requiredField: DEFAULT_REQUIRED_FIELD,
  },
  {
    id: uuidv4(),
    type: "number",
    icon: t.blocks.icons.numbersIcon,
    title: t.blocks.title.numbersText,
    subtitle: t.blocks.title.numbersText,
    supportText: t.blocks.support.numbersText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: {
      defaultValue: DEFAULT_DEFAULT_VALUE,
      isNegative: false,
      listLooks: "Целое",
    },
  },
  {
    id: uuidv4(),
    type: "contacts",
    icon: t.blocks.icons.contactsIcon,
    title: t.blocks.title.contactsText,
    subtitle: t.blocks.title.contactsText,
    supportText: t.blocks.support.contactsText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { maxContacts: 10 },
  },
  {
    id: uuidv4(),
    type: "links",
    icon: t.blocks.icons.linksIcon,
    title: t.blocks.title.linkText,
    subtitle: t.blocks.title.linkText,
    supportText: t.blocks.support.linkText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { defaultValue: DEFAULT_DEFAULT_VALUE, maxLinks: 10 },
  },
  {
    id: uuidv4(),
    type: "date",
    icon: t.blocks.icons.dateIcon,
    title: t.blocks.title.dateText,
    subtitle: t.blocks.title.dateText,
    supportText: t.blocks.support.dateText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { dateModel: { isDateRange: false, isLimitRange: false } },
  },
  {
    id: uuidv4(),
    type: "file",
    icon: t.blocks.icons.fileIcon,
    title: t.blocks.title.fileText,
    subtitle: t.blocks.title.fileText,
    supportText: t.blocks.support.fileText,
    requiredField: DEFAULT_REQUIRED_FIELD,
    settings: { fileModel: { maxSize: 20, maxFiles: 20 } },
  },
]);
